name = "app-emergencia"
main = "worker.js"
compatibility_date = "2026-07-30"

[assets]
directory = "."
binding = "ASSETS"

[[kv_namespaces]]
binding = "APP_KV"
id = "78ef238981024e63b649db88eac1751f"
